# https://taskfile.dev

version: '3'

vars:
  REGISTRY: ghcr.io
  SKILLS_BASE_REPOSITORY: arconia-io/agent-skills
  VERSION: '{{.VERSION | default "latest"}}'

tasks:
  default:
    cmds:
      - task --list
    silent: true

  skills:publish:
    desc: Publish the Skills artifacts to the registry
    cmds:
      - |
        arconia skills push --all \
          --ref {{.REGISTRY}}/{{.SKILLS_BASE_REPOSITORY}} \
          --path skills \
          --tag {{.VERSION}} \
          --additional-tag latest \
          --output-report publish-skills-report.json

  skills:sign:
    desc: Sign the Skills artifacts with Cosign
    cmds:
      - |
        jq -r '.artifacts[] | "\(.ref | split(":")[0])@\(.digest)"' publish-skills-report.json | while read -r artifact; do
          cosign sign --yes "$artifact"
        done

  collection:publish:
    desc: Publish the Skills Collection artifact to the registry
    cmds:
      - |
        arconia skills collection push \
          --name arconia-skills-collection \
          --ref {{.REGISTRY}}/{{.SKILLS_BASE_REPOSITORY}}/collection \
          --tag {{.VERSION}} \
          --additional-tag latest \
          --from-report publish-skills-report.json \
          --output-report publish-skills-collection-report.json

  collection:sign:
    desc: Sign the Skills Collection artifacts with Cosign
    cmds:
      - |
        jq -r '.artifacts[] | "\(.ref | split(":")[0])@\(.digest)"' publish-skills-collection-report.json | while read -r artifact; do
          cosign sign --yes "$artifact"
        done
